### ISSUE TITLE
No such file or directory: 'ArtLine_650.pkl'

### ISSUE THREAD

**Issue by awolfly9** [jwenjian/artline-demo#8] opened 2021-01-08 03:15 UTC
artline-demo git:(main) ✗ python app.py
Traceback (most recent call last):
  File "app.py", line 29, in <module>
    pl.load_pkl()
  File "app.py", line 24, in load_pkl
    learn = load_learner(path, 'ArtLine_650.pkl')
  File "/Users/lgq/.local/share/virtualenvs/artline-demo-gL78j4yU/lib/python3.7/site-packages/fastai/basic_train.py", line 621, in load_learner
    state = torch.load(source, map_location='cpu') if defaults.device == torch.device('cpu') else torch.load(source)
  File "/Users/lgq/.local/share/virtualenvs/artline-demo-gL78j4yU/lib/python3.7/site-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/lgq/.local/share/virtualenvs/artline-demo-gL78j4yU/lib/python3.7/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/lgq/.local/share/virtualenvs/artline-demo-gL78j4yU/lib/python3.7/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'ArtLine_650.pkl'

**Comment by jwenjian** [comment] 2021-01-08 03:17
Duplicate of #5

**Closed as completed by jwenjian** 2021-01-08 03:17 UTC
